name: Go CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Install ALSA dev
        run: |
          sudo apt-get update
          sudo apt-get -y install libasound2-dev

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build cli
        run: make

      - name: Testing translator package
        run: cd ./pkg/translator && go test -v
